Промежуточный этап реализации меню игры.
karaul0f/antEngine pull request #3
Opened 2021-08-16 16:17 UTC by antuor

Добавления контейнера с элементами меню.

2021-08-24 14:27 UTC, antuor commented
Я добавил в файл AudioPlayer.cpp в метод Init вызов метода SetVolume(50) для того чтобы установить громкость звука на 50 при загрузке игры. Возможно стоит перенести установку громкости звука в другое место, например в главное окно

2021-08-25 16:48 UTC, karaul0f commented on Binaries/Data/Windows/MainMenu.txt
> +Button.Button1 {
Дать более осмысленные имена всем элементам. Например, Button.Play.

2021-08-25 16:50 UTC, karaul0f commented on Code/Audio/AudioPlayer.cpp
> +	SetVolume(50);
Загрузка/запись громкости должна происходить из ini-файла. Возможно, в будущем стоит подумать над дубликатом config.ini для сброса громкости.

2021-08-25 16:53 UTC, karaul0f commented on Code/GUI/Windows/MainMenuWindow.cpp
> +	Audio::AudioPlayer::Instance().SetVolume(sliderElement->getValue());
В реализации метода SetVolume производить запись в ini-файл.

2021-08-25 16:57 UTC, karaul0f commented on Code/GUI/Windows/MainMenuWindow.h
> +		//
Похоже на, опечатку. Надо убрать.

2021-08-25 16:58 UTC, karaul0f requested changes
доработать

2021-08-27 14:12 UTC, antuor commented
В файле main поменял порядок инициализации подсистем. Теперь Audio инициализируется до Render для того, что бы считать значение уровня звука из файла, а затем применить его на слайдер в главном окне.

2021-08-28 12:14 UTC, karaul0f commented on Code/Main.cpp
> +	Audio::AudioPlayer::Instance().PlayMusic(Resources::ResourceManager::Instance().GetMusicByName("Music0"), false);
Перенести в Activate() MainMenuWindow. Также прописать остановку музыки в Deactivate

2021-08-30 06:31 UTC, karaul0f commented on Code/Audio/AudioPlayer.h
> +		Core::Ini	m_soundSettings;
По хорошему, надо доработать класс Ini-файла, раз мы не сделали отдельные конфиги под переменные. 

 Класс Ini должен взять на себя функцию промежуточной переменной m_volumeLevel в том числе. 
В самом же классе Ini должна быть проверка, чтобы мы без лишней необходимости повторно не считывали переменную из файла. 

 Резюмирую, избавляемся от промежуточной переменной m_volumeLevel и используем m_soundSettings (прежде переименованный в m_volumeLevel).

2021-08-30 06:33 UTC, karaul0f requested changes
Доработать. Не настаиваю, но лучше доработать класс Ini файла, возможно таки использовать шаблоны.

2021-08-30 17:57 UTC, karaul0f approved these changes

2021-08-30 17:58 UTC, merged